CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# enable display drivers
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y

#EXT POWER
CONFIG_ZMK_EXT_POWER=y

#EC11 enable
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_ZMK_POINTING=y